"""modified server schema

Revision ID: 528f89445caa
Revises: a870f5253754
Create Date: 2021-10-27 20:01:58.927807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528f89445caa'
down_revision = 'a870f5253754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('server', sa.Column('webserver_ip', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'webserver_ip')
    op.drop_column('server', 'access_token')
    # ### end Alembic commands ###
