"""Added Mysql query connection info to mysql_query_server_assignment table and removed the same one from mysql_query

Revision ID: 7ab6d532dce9
Revises: c2dae6d22595
Create Date: 2021-10-30 17:06:26.793712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ab6d532dce9'
down_revision = 'c2dae6d22595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mysql_query', 'mysql_host')
    op.drop_column('mysql_query', 'mysql_database')
    op.drop_column('mysql_query', 'mysql_username')
    op.drop_column('mysql_query', 'mysql_port')
    op.drop_column('mysql_query', 'mysql_password')
    op.add_column('mysql_query_server_assignment', sa.Column('mysql_username', sa.Text(), nullable=True))
    op.add_column('mysql_query_server_assignment', sa.Column('mysql_password', sa.Text(), nullable=True))
    op.add_column('mysql_query_server_assignment', sa.Column('mysql_host', sa.Text(), nullable=True))
    op.add_column('mysql_query_server_assignment', sa.Column('mysql_port', sa.Text(), nullable=True))
    op.add_column('mysql_query_server_assignment', sa.Column('mysql_database', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mysql_query_server_assignment', 'mysql_database')
    op.drop_column('mysql_query_server_assignment', 'mysql_port')
    op.drop_column('mysql_query_server_assignment', 'mysql_host')
    op.drop_column('mysql_query_server_assignment', 'mysql_password')
    op.drop_column('mysql_query_server_assignment', 'mysql_username')
    op.add_column('mysql_query', sa.Column('mysql_password', mysql.TEXT(), nullable=True))
    op.add_column('mysql_query', sa.Column('mysql_port', mysql.TEXT(), nullable=True))
    op.add_column('mysql_query', sa.Column('mysql_username', mysql.TEXT(), nullable=True))
    op.add_column('mysql_query', sa.Column('mysql_database', mysql.TEXT(), nullable=True))
    op.add_column('mysql_query', sa.Column('mysql_host', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
