"""added extra fields to assignment table

Revision ID: 94b1212011bc
Revises: e7f1f6d9a737
Create Date: 2021-10-27 21:59:34.447345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b1212011bc'
down_revision = 'e7f1f6d9a737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mysql_query_server_assignment', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('mysql_query_server_assignment', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mysql_query_server_assignment', 'notes')
    op.drop_column('mysql_query_server_assignment', 'name')
    # ### end Alembic commands ###
