"""Newest revision

Revision ID: a870f5253754
Revises: 25481cc98b36
Create Date: 2021-10-26 22:51:19.657941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a870f5253754'
down_revision = '25481cc98b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
