"""Added Mysql query connection info to mysql_query table

Revision ID: c2dae6d22595
Revises: 94b1212011bc
Create Date: 2021-10-30 17:02:49.450156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dae6d22595'
down_revision = '94b1212011bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mysql_query', sa.Column('mysql_username', sa.Text(), nullable=True))
    op.add_column('mysql_query', sa.Column('mysql_password', sa.Text(), nullable=True))
    op.add_column('mysql_query', sa.Column('mysql_host', sa.Text(), nullable=True))
    op.add_column('mysql_query', sa.Column('mysql_port', sa.Text(), nullable=True))
    op.add_column('mysql_query', sa.Column('mysql_database', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mysql_query', 'mysql_database')
    op.drop_column('mysql_query', 'mysql_port')
    op.drop_column('mysql_query', 'mysql_host')
    op.drop_column('mysql_query', 'mysql_password')
    op.drop_column('mysql_query', 'mysql_username')
    # ### end Alembic commands ###
