"""added mysql query to server linking

Revision ID: e7f1f6d9a737
Revises: 528f89445caa
Create Date: 2021-10-27 21:35:37.441681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f1f6d9a737'
down_revision = '528f89445caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mysql_query_server_assignment',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('mysql_query_id', sa.BigInteger(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('query_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mysql_query_id'], ['mysql_query.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('server_id', 'mysql_query_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mysql_query_server_assignment')
    # ### end Alembic commands ###
